### ISSUE TITLE
Empty/missing Kubernetes securityContexts

### ISSUE THREAD

**Issue by lianhao** [opea-project/GenAIInfra#129]
This is to track issue opea-project/GenAIExamples#258

- [x] helm chart modification. (Done)
- [ ] manifest modification: (On hold) Manifest should be generated by 'helm tempalte' in theory. Currently, we're in the process of discussion of how manifest will be generated and leveraged by GMC. We'll hold this until that discussion has been resolved.
- [x] (07/02/24): need to verify whether readOnlyRootFilesystem: ture is working on all our component helm charts

**Comment by daisy-ycguo** [comment]
I think this is done. Close it.
