### ISSUE TITLE
Bug for the generation of microservice name defined in GMC CR yaml file.

### ISSUE THREAD

**Issue by zhlsunshine** [opea-project/GenAIInfra#138]
GMC can define the microservice name for every steps in CR YAML file , however, the connection between microservices may be incorrect if the microservice names are not match the name in microservice template YAML files.
Therefore, there are some bugs for it. And need to fix.

**Comment by zhlsunshine** [comment]
For make the e2e test of codegen and codetrans examples can be passed, I have to fix this problem by [PR#139](https://github.com/opea-project/GenAIInfra/pull/139)

**Comment by daisy-ycguo** [comment]
@zhlsunshine is this issue resolved? if so, please close it.

**Comment by irisdingbj** [comment]
yes. this is fixed via https://github.com/opea-project/GenAIInfra/pull/139. Let's close it now
