### ISSUE TITLE
GMC failed to continue the process if there's branch or switch case happen in the middle of the pipeline.

### ISSUE THREAD

**Issue by hteeyeoh** [opea-project/GenAIInfra#143]
GMC failed to continue the process if there's switch case happen in the middle of the pipeline. 
For example: chatqna pipeline. If we include two embedding models for switch case, it does not able to continue process for the following and it will just finish/exit the pipeline once embedding process finish.
[embedding_model_switch.txt](https://github.com/user-attachments/files/16049339/embedding_model_switch.txt)

**Comment by KfreeZ** [comment]
@hteeyeoh does #152 fix the issue? if not, please provide more details, thank you.

**Comment by hteeyeoh** [comment]
@KfreeZ , ya i think this issue we are still not able to validate due to the dependencies in microservices where it hardcoded the path in env to select the downstream service. But according to our last work session together with Huailong, he did mentioned this changes will fix this issue. But this has not been really validate due to the limitation above. You may mark this issue as resolved for now. Will recreate in future when we have solution for the issue above then we can test on that time.
Thank you.

**Comment by KfreeZ** [comment]
> @KfreeZ , ya i think this issue we are still not able to validate due to the dependencies in microservices where it hardcoded the path in env to select the downstream service. But according to our last work session together with Huailong, he did mentioned this changes will fix this issue. But this has not been really validate due to the limitation above. You may mark this issue as resolved for now. Will recreate in future when we have solution for the issue above then we can test on that time. Thank you.

https://github.com/opea-project/GenAIInfra/issues/166 is created and I am working on it

**Comment by daisy-ycguo** [comment]
Is this issue resloved? @KfreeZ @zhlsunshine If it is, please close it.

**Comment by KfreeZ** [comment]
> Is this issue resloved? @KfreeZ @zhlsunshine If it is, please close it.

@hteeyeoh please close it if you think this is resolved

**Comment by hteeyeoh** [comment]
> > Is this issue resloved? @KfreeZ @zhlsunshine If it is, please close it.
> 
> @hteeyeoh please close it if you think this is resolved

Yes. Tested with latest yaml from main branch. The issue is resolved with the latest changes (https://github.com/opea-project/GenAIInfra/issues/166) . Closing the ticket.
