### ISSUE TITLE
Redesign the way how common microservice installed and talk

### ISSUE THREAD

**Issue by bjzhjing** [opea-project/GenAIInfra#147]
There are two issues observed while try to install each microservice under ./heml-chars/common:

- Microservice like retriever-usvc has dependency specified in Chart.yaml, but embedding is missed there.
- Even if I install microservices - redis-vector-db and embedding-usvc firstly, retriever-usvc can not talk to them, it will deploy the former microservices itself and then talk to them.

Based on above issues, I'm thinking if we could install the common microservices separately. That is to install each microservice in order, and then they can talk to each other, rather than deploy the same service again and again.

**Comment by yongfengdu** [comment]
Thanks for reporting this issue.
Originally there are less components, so hard dependency is set to ease the deployment configurations for GenAIExamples.
But with more components added, and user may want more flexible configuration during deployment, so it's time to remove these hard dependencies.
The helm chart dependency should only be set in the E2E application examples like ChatQnA
Will clean up this.
