### ISSUE TITLE
CI requirement: enhance CI e2e cases' debugability

### ISSUE THREAD

**Issue by lianhao** [opea-project/GenAIInfra#154]
Currently when a e2e test fails in CI, it's very difficult to find out the reason why it's failing, because all the valuable information is either in K8S pod status and/or pod logs. We should enhance CI as follows:

- when a e2e test fails during the workload deployment phase, we should shows all the pod/container status, at least for those non-running pod/containers, as well as the logs of those terminated container

    i.e. kubectl get pods --all-namespaces -o go-template='{{ range  $item := .items }}{{ range .status.conditions }}{{ if (or (and (eq .type "PodScheduled") (eq .status "False")) (and (eq .type "Ready") (eq .status "False"))) }}{{ $item.metadata.name}} {{ end }}{{ end }}{{ end }}'

- when a e2e test fails during the request submit/response validation phase, we should shows all the pod status as well as all the container logs

In this way, we can root cause the e2e tests failiures without touching the backend K8S infra.

**Comment by daisy-ycguo** [comment]
Agree. We shall dump more information to CI logs. GMC e2e is a good example to follow.
