### ISSUE TITLE
GMC opearator doesn't reflect 

### ISSUE THREAD

**Issue by Jiangbo-W** [opea-project/GenAIInfra#192]
- Even with ChatQnA deployment failure, GMC still reports 8 components are ready. No healthy checking. Customer may fail to send requests to the pipeline. 
- Add health probe for the pipeline and keep the consistency with pipeline. GMC needs to assist users in maintaining the availability and consistency of the pipeline.

![image](https://github.com/user-attachments/assets/2ab29066-4c2e-4d8d-8ad9-d134a210d355)

**Comment by KfreeZ** [comment]
https://github.com/opea-project/GenAIInfra/pull/117 this PR will fix this

**Comment by KfreeZ** [comment]
> #117 this PR will fix this

117 is deprecated, #259 is the fix, since it's merged, close this issue
