### ISSUE TITLE
GMC operator doesn’t give pipeline details at deployment and running. 

### ISSUE THREAD

**Issue by Jiangbo-W** [opea-project/GenAIInfra#193]
- Provide more details of stages, status and failure reason and error codes for user’s understanding and debugging. GMC operators should maintain the status of the pipeline than installation only.

![image](https://github.com/user-attachments/assets/5842f36c-52ff-4805-9288-09a0bb37092f)

**Comment by KfreeZ** [comment]
@Jiangbo-W we have get the mode detailed information of the resources in GMC's status, please try the latest image and latest doc, to see if there is ok for you. Thanks

**Comment by xiguiw** [comment]
@Jiangbo-W 
Could we close this?
