### ISSUE TITLE
Avoid using hostPath as container storage.

### ISSUE THREAD

**Issue by Jiangbo-W** [opea-project/GenAIInfra#195]
Firstly, if the directory does not exist on the host, it will cause the container to fail to run. Users need to log in to each machine in the cluster to create this directory, which requires the password for each machine. 

Additionally, it will have to download and maintain multiple copy of models and dataset in each node of a cluster. Slow and cause version control issues and not secure.

![image](https://github.com/user-attachments/assets/06a2a021-1ce5-4387-8bc8-16ebecc33e9c)
![image](https://github.com/user-attachments/assets/4c7ec992-94e1-4a27-bc6a-f13adb936dfa)

**Comment by endomorphosis** [comment]
I did see this error, and fixed it myself, but for programmatic deployment, this should be taken into consideration.

**Comment by lianhao** [comment]
Yes this is issue for us to tackle. We've already have created issue #128 for this

**Comment by yongfengdu** [comment]
Completed supporting PersistentVolumeClaim as the model cache storage at #128 
Also by default, we'll use temp volume instead of HostPath.
