### ISSUE TITLE
Support internal/local embedding in dataprep-redis

### ISSUE THREAD

**Issue by irisdingbj** [opea-project/GenAIInfra#208]
By default GenAIExamples docker version will not use TEI_ENDPOINT,  we need align this

**Comment by lianhao** [comment]
The TEI_ENDPOINT is used by dataprep-redis service. By looking at the [dataprep-redis code](https://github.com/opea-project/GenAIComps/blob/main/comps/dataprep/redis/langchain/prepare_doc_redis.py#L133), I think what we need to change is the opposite of removing TEI_ENPOINT,  but add a new environment of EMBED_MODEL to allow users to change the embedding models if they want. Any comment @irisdingbj
