### ISSUE TITLE
horizontal scaling broken without podAntiAffinity rules.

### ISSUE THREAD

**Issue by endomorphosis** [opea-project/GenAIInfra#218]
Horizontal scaling is broken, because kubernetes attempts to scale multiple containers on the same machine, thus each of the manifest files should include podAntiAffinity rules e.g. 

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: redis-vector-db
                app.kubernetes.io/instance: redis-vector-db
            topologyKey: "kubernetes.io/hostname"

**Comment by lianhao** [comment]
will add them in next release

**Comment by lianhao** [comment]
I just checked, pod antiaffinity is already supported in helm chart, just define the affinity.podAntiAffinity in the helm chart values will do.

@endomorphosis  how did you deploy the workload?

**Comment by endomorphosis** [comment]
I wasn't using the helm chart but the manifests

**Comment by lianhao** [comment]
Please use helm chart to deploy for podAntiAffinity rules. Since this rules are depends on each user's specific requirements, there is no way to hard code it into manifest.

I'll close this bug for now. Please feel free to reopen it is needed.
