### ISSUE TITLE
OPEA/ASR:latest permissions

### ISSUE THREAD

**Issue by endomorphosis** [opea-project/GenAIInfra#221]
Normal   Pulling                 8s                      kubelet            Pulling image "opea/asr:latest"
  Warning  Failed                  7s                      kubelet            Failed to pull image "opea/asr:latest": Error response from daemon: pull access denied for opea/asr, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed                  7s                      kubelet            Error: ErrImagePull

**Comment by lianhao** [comment]
This should be resolved when m3 is released by the end July when opea/asr image is published.

**Comment by daisy-ycguo** [comment]
can we close it? @endomorphosis

**Comment by daisy-ycguo** [comment]
It is not an issue of GenAIInfra. opea/asr image will be published soon. Close it.
