### ISSUE TITLE
Permission issue of data-prep container image in helm chart

### ISSUE THREAD

**Issue by LeiZhou-97** [opea-project/GenAIInfra#234]
When I try to upload the doc that contains the image, the data-prep pod needs to makedir `/img`. But under current deployment **securitycontext**, it will cause permissiondenied.

**Comment by lianhao** [comment]
Currently, we're hitting another blocking issue opea-project/GenAIComps#398 in data-prep. We need to wait for that issue to be resolved so we can continue debug this.

**Comment by lianhao** [comment]
I've confirmed that this is an issue in GenAIComps, and is not related to any K8S securityContext. This is reproducible in docker environment too. Please see issue opea-project/GenAIComps#407

**Comment by lianhao** [comment]
I'm close this issue here, since it's an issue belonging to GenAIComps and is being tracked there
