### ISSUE TITLE
need to automatically populating internal service name into no_proxy env if proxy is being set

### ISSUE THREAD

**Issue by kushal2705** [opea-project/GenAIInfra#255]
when ChatQnA is deployed using helm, its observed that `chatqna-retriever-usvc` pod keep crashing with below error 

`Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
Parsing 10k filing doc for NIKE data/nke-10k-2023.pdf
Done preprocessing. Created  270  chunks of the original pdf
Error embedder is unavailable: 504 Server Error: Gateway Timeout for url:
http://chatqna-tei/
Embedder endpoint is not available. Checking again in 5 seconds...
Error embedder is unavailable: 504 Server Error: Gateway Timeout for url:
http://chatqna-tei/
Embedder endpoint is not available. Checking again in 5 seconds...
Error embedder is unavailable: 504 Server Error: Gateway Timeout for url:
http://chatqna-tei/
Embedder endpoint is not available. Checking again in 5 seconds..`

@lianhao suggestion to fix proxy setting worked . Upon adding names of all the ChatQnA pods into global `no_proxy` , all pods started to function well .
 https://github.com/opea-project/GenAIInfra/blob/af47b3c0fec0315a942f091e5e0854c9badb8519/helm-charts/chatqna/values.yaml#L40

**Comment by lianhao** [comment]
This is actually related of automatically populating no_proxy with correct west-east endpoint svc names if users have ever set http_proxy and/or https_proxy.

**Comment by kushal2705** [comment]
@lianhao Sure
