### ISSUE TITLE
when accessing the pipeline the reply is not being streamed to the user

### ISSUE THREAD

**Issue by jpiaseck** [opea-project/GenAIInfra#263]
When following instructions:
https://github.com/opea-project/GenAIInfra/blob/main/microservices-connector/usage_guide.md

export CLIENT_POD=$(kubectl get pod  -l app=client-test -o jsonpath={.items..metadata.name})  //BTW there is -A missing should be #kubectl get pod -A -l app=client-test
export accessUrl=$(kubectl get gmc -n chatqa -o jsonpath="{.items[?(@.metadata.name=='chatqa')].status.accessUrl}")
kubectl exec "$CLIENT_POD" -n chatqa -- curl $accessUrl  -X POST  -d '{"text":"What is the revenue of Nike in 2023?","parameters":{"max_new_tokens":17, "do_sample": true}}' -H 'Content-Type: application/json'

getting
![image](https://github.com/user-attachments/assets/b338e8a6-0caf-4922-95bb-bbc7ea9e88fb)

What is the curl download doing here?
We need to stream output to the user , not wait for entire reply to be downloaded from anywhere.

**Comment by KfreeZ** [comment]
Hi @jpiaseck thanks for you questions.
The curl in this guide is to demonstrate that the pipeline is working.
Essentially, there will be a better client or UI to do the streaming.

**Comment by jpiaseck** [comment]
@KfreeZ we are preparing Demo on intel Vision  (24.09) where Pat would be demonstrating the the chatqna solution on RAG for enterprises.
We need to deploy the RAG pipeline and we are just discussing different option of deployment.
Is there some roadmap regarding new features coming to OPEA?
For example when do we plan to have option of streaming added to deployment with gmcconnector (which we believe is much better option than using helm charts)?

**Comment by KfreeZ** [comment]
add @irisdingbj @mkbhanda here 
I think we could talk internally for intel event, since this is an opensource space.
And my question is where you want to deploy the RAG solution, on AI PC or some cluster?

**Comment by zhlsunshine** [comment]
Yeah, thanks @jpiaseck to point it out,  I think you can use below command to skip the extra output of `curl download` you mentioned above: 
 `kubectl exec "$CLIENT_POD" -n chatqa -- curl -s $accessUrl -X POST -d '{"text":"What is the revenue of Nike in 2023?","parameters":{"max_new_tokens":17, "do_sample": true}}' -H 'Content-Type: application/json'`

The difference is that adding `-s` to be silent when doing the query.
