### ISSUE TITLE
[ci-auto] GenAIExample ChatQnA,CodeGen,CodeTrans,DocSum,FaqGen,SearchQnA,Translation compose.yaml got changed.

### ISSUE THREAD

**Issue by daisy-ycguo** [opea-project/GenAIInfra#277]
## GenAIExample ChatQnA,CodeGen,CodeTrans,DocSum,FaqGen,SearchQnA,Translation compose.yaml got changed

Below files are changed in [this commit](https://github.com/opea-project/GenAIExamples/commit/88eeb0d7e6a800680ec9891e91087461026ffcad)

- ChatQnA/docker/aipc/compose.yaml
- ChatQnA/docker/gaudi/compose.yaml
- ChatQnA/docker/gpu/compose.yaml
- ChatQnA/docker/xeon/compose.yaml
- CodeGen/docker/gaudi/compose.yaml
- CodeGen/docker/xeon/compose.yaml
- CodeTrans/docker/gaudi/compose.yaml
- CodeTrans/docker/xeon/compose.yaml
- DocSum/docker/gaudi/compose.yaml
- DocSum/docker/xeon/compose.yaml
- FaqGen/docker/gaudi/compose.yaml
- FaqGen/docker/xeon/compose.yaml
- SearchQnA/docker/gaudi/compose.yaml
- SearchQnA/docker/xeon/compose.yaml
- Translation/docker/xeon/compose.yaml

Please verify if the helm charts and manifests need to be changed accordingly.

> This issue was created automatically by CI.

**Comment by lianhao** [comment]
They disabled langsmith tracing support which is disabled by default in the helm charts. No need to update.
