### ISSUE TITLE
[ci-auto] GenAIExample FaqGen compose.yaml got changed.

### ISSUE THREAD

**Issue by daisy-ycguo** [opea-project/GenAIInfra#279]
## GenAIExample FaqGen compose.yaml got changed

Below files are changed in [this commit](https://github.com/opea-project/GenAIExamples/commit/5ac77f78dabe773870a68e9d77c3b0554ab8035c)

- FaqGen/docker/xeon/compose.yaml

Please verify if the helm charts and manifests need to be changed accordingly.

> This issue was created automatically by CI.

**Comment by lianhao** [comment]
won't result any change in this side
