### ISSUE TITLE
[ci-auto] Support visualQnA

### ISSUE THREAD

**Issue by daisy-ycguo** [opea-project/GenAIInfra#284]
## GenAIExample VisualQnA compose.yaml got changed

Below files are changed in [this commit](https://github.com/opea-project/GenAIExamples/commit/2390920b1dc445ecff4fd8177b61b42711d8f898)

- VisualQnA/docker/gaudi/compose.yaml
- VisualQnA/docker/xeon/compose.yaml

Please verify if the helm charts and manifests need to be changed accordingly.

> This issue was created automatically by CI.

**Comment by yongfengdu** [comment]
#505
