### ISSUE TITLE
[ci-auto] Find common tgi user settings and make them configurable by different values

### ISSUE THREAD

**Issue by daisy-ycguo** [opea-project/GenAIInfra#297]
## GenAIExample FaqGen compose.yaml got changed

Below files are changed in [this commit](https://github.com/opea-project/GenAIExamples/commit/80e3e2a2d3120c7761a42991b7742c2085a295bd)

- FaqGen/docker/gaudi/compose.yaml

Please verify if the helm charts and manifests need to be changed accordingly.

> This issue was created automatically by CI.

We need to find common user configurable items in both tgi and tgi-gaudi, and expose them as env to be configured differently by different workloads

**Comment by lianhao** [comment]
we plan to postpone this to M5 until we support faqgen

**Comment by lianhao** [comment]
PR #402 and #528 should have resolved this
