### ISSUE TITLE
[ci-auto] GenAIExample AudioQnA,ChatQnA,CodeGen,CodeTrans,DocSum,FaqGen,SearchQnA,Translation,VisualQnA compose.yaml got changed.

### ISSUE THREAD

**Issue by daisy-ycguo** [opea-project/GenAIInfra#334]
## GenAIExample AudioQnA,ChatQnA,CodeGen,CodeTrans,DocSum,FaqGen,SearchQnA,Translation,VisualQnA compose.yaml got changed

Below files are changed in [this commit](https://github.com/opea-project/GenAIExamples/commit/6674832162f1d436c83b51397873306ccdb6a48d)

- AudioQnA/docker/xeon/compose.yaml
- ChatQnA/docker/xeon/compose.yaml
- CodeGen/docker/xeon/compose.yaml
- CodeTrans/docker/xeon/compose.yaml
- DocSum/docker/xeon/compose.yaml
- FaqGen/docker/xeon/compose.yaml
- SearchQnA/docker/xeon/compose.yaml
- Translation/docker/xeon/compose.yaml
- VisualQnA/docker/xeon/compose.yaml

Please verify if the helm charts and manifests need to be changed accordingly.

> This issue was created automatically by CI.

**Comment by lianhao** [comment]
we'll stick to tgi version 2.2.0 until 2.3.0 is released
