### ISSUE TITLE
update_manifests.sh generates wrong endpoint names

### ISSUE THREAD

**Issue by eero-t** [opea-project/GenAIInfra#337]
This is for today's HEAD of `GENAIInfra`.

Use-case:
* Update manifests: `cd helm-charts; ./update_manifests.sh`
* Check generated service endpoint names: `cd ../microservices-connector/config/manifests/; grep ENDPOINT *.yaml`
* Deploy generated manifests to cluster and check resulting service names: `kubectl get svc`

Expected outcome:
* Generated ENDPOINT variables match service names for given endpoints, and services work

Actual outcome:
* Service logs are full of timeouts / queries failing
* Service names in ENDPOINT variables are prefixed with the _calling_ service name, but actual service names are not
  * E.g. `TGI_LLM_ENDPOINT` variable value in `llm-uservice.yaml` manifest is `http://llm-uservice-tgi` instead of actual `http://tgi` (`.default.svc.cluster.local`)

**Comment by eero-t** [comment]
This seems to be a bug in the script, not in the Helm charts?

When I generate manifests directly with `helm template chatqna chatqna --skip-tests ...` things match.

**Comment by lianhao** [comment]
The generated manifest files from ./update_manifests.sh are for **_GMC USE ONLY_**. I wouldn't suggest to use them directly. If you want to deploy each component microservice separately, please use helm charts under `helm-charts/common` directly.

@eero-t you're absolutely right. The devil is in the ./update_manifests.sh. We'll discuss with GMC folks in next cycle to see if we can make the generated manifest files usable for non GMC users.

**Comment by eero-t** [comment]
I see. "Generate manifests from Helm Charts" section in the directory [README](https://github.com/opea-project/GenAIInfra/tree/main/helm-charts) only talks about looking into `update_manifests.sh`, not about using it... :-)

**Comment by eero-t** [comment]
Btw. the table in that README has has wrong link name ("Code generation") for `chatqna`.

**Comment by yongfengdu** [comment]
Fixes in README to avoid confusion 
#343
