### ISSUE TITLE
[helm-charts] Use latest docker image for main branch

### ISSUE THREAD

**Issue by yongfengdu** [opea-project/GenAIInfra#341]
The current default image tag is the same as OPEA release. Since we'll have different branch for each release, we can use the following rules for docker image tag:
main branch: Use latest, so we can run with latest image to detect issues early.
stable branch (v0.9 etc): Use the docker images aligned with OPEA release.

When a new release is created, we'll trigger a CI job to modify the release branch accordingly.

**Comment by lianhao** [comment]
close as the PR has been merged
