### ISSUE TITLE
Support nginx reverse proxy in helm e2e chart for UI

### ISSUE THREAD

**Issue by daisy-ycguo** [opea-project/GenAIInfra#368]
Take PR opea-project/GenAIExamples/pull/609 as a reference, we need to support niginx reverse proxy in our helm e2e chart. Instead of using the [opea nginx](https://github.com/opea-project/GenAIComps/tree/main/comps/nginx), we can use upstream nginx and render the nginx.conf in our e2e helm chart support.

- [ ] Investigate if nginx reverse proxy can avoid CORS issue for traditional UI
- [ ] If there is no CORS issue, add nginx reverse proxy along with UI in all the 4 helm e2e chart

**Comment by lianhao** [comment]
Closes it as PR #377 and PR #415 is merged
