### ISSUE TITLE
support tei-rerank on gaudi

### ISSUE THREAD

**Issue by lianhao** [opea-project/GenAIInfra#369]
Since tei-gaudi [v1.5.0 image](https://github.com/huggingface/tei-gaudi/pkgs/container/tei-gaudi/264169892?tag=1.5.0) has been released, we need to verify it support reranking on gaudi. And if so, we need to support that in our helm chart/manifest.

**Comment by xiguiw** [comment]
@lianhao 
Reranking is enabled on Gaudi.
Could this be closed?
