### ISSUE TITLE
[ci-auto] GenAIExample AgentQnA,AudioQnA,ChatQnA,CodeGen,CodeTrans,DocIndexRetriever,DocSum,FaqGen,ProductivitySuite,SearchQnA,Translation,VisualQnA compose.yaml got changed.

### ISSUE THREAD

**Issue by daisy-ycguo** [opea-project/GenAIInfra#421]
## GenAIExample AgentQnA,AudioQnA,ChatQnA,CodeGen,CodeTrans,DocIndexRetriever,DocSum,FaqGen,ProductivitySuite,SearchQnA,Translation,VisualQnA compose.yaml got changed

Below files are changed in [this commit](https://github.com/opea-project/GenAIExamples/commit/d73129cbf0958ba47c6fac242e2702a679ab9181)

- AgentQnA/docker_compose/intel/cpu/xeon/compose_openai.yaml
- AudioQnA/docker_compose/intel/cpu/xeon/compose.yaml
- AudioQnA/docker_compose/intel/hpu/gaudi/compose.yaml
- ChatQnA/docker_compose/intel/cpu/aipc/compose.yaml
- ChatQnA/docker_compose/intel/cpu/xeon/compose.yaml
- ChatQnA/docker_compose/intel/cpu/xeon/compose_no_wrapper.yaml
- ChatQnA/docker_compose/intel/cpu/xeon/compose_qdrant.yaml
- ChatQnA/docker_compose/intel/cpu/xeon/compose_vllm.yaml
- ChatQnA/docker_compose/intel/cpu/xeon/compose_without_rerank.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_guardrails.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_no_wrapper.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_vllm.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_vllm_ray.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_without_rerank.yaml
- ChatQnA/docker_compose/nvidia/gpu/compose.yaml
- CodeGen/docker_compose/intel/cpu/xeon/compose.yaml
- CodeGen/docker_compose/intel/hpu/gaudi/compose.yaml
- CodeTrans/docker_compose/intel/cpu/xeon/compose.yaml
- CodeTrans/docker_compose/intel/hpu/gaudi/compose.yaml
- DocIndexRetriever/docker_compose/intel/cpu/xeon/compose.yaml
- DocIndexRetriever/docker_compose/intel/hpu/gaudi/compose.yaml
- DocSum/docker_compose/intel/cpu/xeon/compose.yaml
- DocSum/docker_compose/intel/hpu/gaudi/compose.yaml
- FaqGen/docker_compose/intel/cpu/xeon/compose.yaml
- FaqGen/docker_compose/intel/hpu/gaudi/compose.yaml
- ProductivitySuite/docker_compose/intel/cpu/xeon/compose.yaml
- SearchQnA/docker_compose/intel/cpu/xeon/compose.yaml
- SearchQnA/docker_compose/intel/hpu/gaudi/compose.yaml
- Translation/docker_compose/intel/cpu/xeon/compose.yaml
- Translation/docker_compose/intel/hpu/gaudi/compose.yaml
- VisualQnA/docker_compose/intel/cpu/xeon/compose.yaml
- VisualQnA/docker_compose/intel/hpu/gaudi/compose.yaml

Please verify if the helm charts and manifests need to be changed accordingly.

> This issue was created automatically by CI.

**Comment by lianhao** [comment]
just a directory layout change
