### ISSUE TITLE
[ci-auto] Update tei-gaudi and tgi-gaudi to version 1.5.0 and 2.0.5 respectively

### ISSUE THREAD

**Issue by daisy-ycguo** [opea-project/GenAIInfra#453]
## GenAIExample AgentQnA,AudioQnA,ChatQnA,CodeGen,CodeTrans,DocIndexRetriever,DocSum,FaqGen,SearchQnA,Translation,VisualQnA compose.yaml got changed

Below files are changed in [this commit](https://github.com/opea-project/GenAIExamples/commit/3fb60608b30a71e6d08dae499f38a7b6a468bc3f)

- AgentQnA/docker_compose/intel/hpu/gaudi/compose.yaml
- AudioQnA/docker_compose/intel/hpu/gaudi/compose.yaml
- ChatQnA/docker_compose/intel/cpu/xeon/compose_qdrant.yaml
- ChatQnA/docker_compose/intel/cpu/xeon/compose_vllm.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_guardrails.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_no_wrapper.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_vllm.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_vllm_ray.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_without_rerank.yaml
- CodeGen/docker_compose/intel/hpu/gaudi/compose.yaml
- CodeTrans/docker_compose/intel/hpu/gaudi/compose.yaml
- DocIndexRetriever/docker_compose/intel/hpu/gaudi/compose.yaml
- DocSum/docker_compose/intel/hpu/gaudi/compose.yaml
- FaqGen/docker_compose/intel/hpu/gaudi/compose.yaml
- SearchQnA/docker_compose/intel/hpu/gaudi/compose.yaml
- Translation/docker_compose/intel/hpu/gaudi/compose.yaml
- VisualQnA/docker_compose/intel/hpu/gaudi/compose.yaml

Please verify if the helm charts and manifests need to be changed accordingly.

> This issue was created automatically by CI.

**Comment by lianhao** [comment]
fixed by #551 and #494
