### ISSUE TITLE
[helm-charts] Merge tei and teirerank helm charts

### ISSUE THREAD

**Issue by yongfengdu** [opea-project/GenAIInfra#472]
tei and teirerank both use ghcr.io/huggingface/text-embeddings-inference, the only difference is Models used.
https://github.com/opea-project/GenAIInfra/tree/main/helm-charts/common/tei
https://github.com/opea-project/GenAIInfra/tree/main/helm-charts/common/teirerank
We can use the same helm charts to avoid maintenance effort.
For cases(ChatQnA) we need to deploy both tei and teirerank services, we can use alias.

**Comment by xiguiw** [comment]
> tei and teirerank both use ghcr.io/huggingface/text-embeddings-inference, the only difference is Models used. https://github.com/opea-project/GenAIInfra/tree/main/helm-charts/common/tei https://github.com/opea-project/GenAIInfra/tree/main/helm-charts/common/teirerank We can use the same helm charts to avoid maintenance effort. For cases(ChatQnA) we need to deploy both tei and teirerank services, we can use alias.

@yongfengdu 
Kindly remind that TEI and Reranking both use the same docker images on Xeon.
But on Gaudi platform, TEI runs on Xeon while Reranking runs on Gaudi. They use different docker images.

**Comment by yongfengdu** [comment]
Thanks, we can handle the docker image difference in one helm chart. But it's better to keep them separately to align with the GenAIComps dir layout.
Close with won't fix.
> @yongfengdu Kindly remind that TEI and Reranking both use the same docker images on Xeon. But on Gaudi platform, TEI runs on Xeon while Reranking runs on Gaudi. They use different docker images.
