### ISSUE TITLE
Add more e2e helm chart examples

### ISSUE THREAD

**Issue by yongfengdu** [opea-project/GenAIInfra#504]
As we are having more GenAIExamples workloads, it's better to support the oneclick helm chart deployment for better user experience.
We're prioritizing these 3 examples at 1.1 release, and will add more.
VisualQnA, AudioQnA, FaqGen

**Comment by joshuayao** [comment]
Hi @yongfengdu, does this feature complete? If so, could we close the ticket? Thanks.

**Comment by yongfengdu** [comment]
Above 3 example completed.
