### ISSUE TITLE
[chatqna] Document upload does not work.

### ISSUE THREAD

**Issue by poussa** [opea-project/GenAIInfra#543]
Installed chatqna via Helm from the git repo [GenAIInfra](https://github.com/opea-project/GenAIInfra) on AWS.

```
helm install -n chatqna --create-namespace chatqna helm-charts/chatqna --set nginx.service.type=LoadBalancer --set global.modelUsePVC=model-volume --set global.HUGGINGFACEHUB_API_TOKEN=${HFTOKEN}
``` 

The UI comes up fine but fails to upload any content, POST to /v1/dataprep gets 400 (Bad Request). This happens when you hit the "Upload" button.

![Screenshot 2024-11-10 at 21 54 50](https://github.com/user-attachments/assets/48ced84e-850d-48c2-98e5-7ef950a61b21)

**Comment by Ruoyu-y** [comment]
Hi, I cannot reproduce the error you met on my local machine. Any log you can find in the chatqna-data-prep-xxxx pod?

**Comment by poussa** [comment]
> Hi, I cannot reproduce the error you met on my local machine (I tried to reproduce the problem on a Xeon server in US). Any log you can find in the chatqna-data-prep-xxxx pod?

Here is the log form the data-prep pod...

`INFO:     10.0.3.115:39626 - "POST /v1/dataprep HTTP/1.0" 400 Bad Request`

**Comment by poussa** [comment]
@Ruoyu-y did you use the same Helm chart command? Or docker compose? Do you run on K8s? Do you use the standard images:
```
      image: opea/chatqna:latest
      image: docker.io/opea/chatqna:latest
      image: opea/chatqna-conversation-ui:1.0
      image: docker.io/opea/chatqna-conversation-ui:1.0
      image: opea/dataprep-redis:1.0
      image: docker.io/opea/dataprep-redis:1.0
      image: opea/embedding-tei:1.0
      image: docker.io/opea/embedding-tei:1.0
      image: opea/llm-tgi:1.0
      image: docker.io/opea/llm-tgi:1.0
      image: nginx:1.27.1
      image: docker.io/library/nginx:1.27.1
      image: redis/redis-stack:7.2.0-v9
      image: docker.io/redis/redis-stack:7.2.0-v9
      image: opea/reranking-tei:1.0
      image: docker.io/opea/reranking-tei:1.0
      image: opea/retriever-redis:1.0
      image: docker.io/opea/retriever-redis:1.0
      image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
      image: ghcr.io/huggingface/text-generation-inference:sha-e4201f4-intel-cpu
```

**Comment by poussa** [comment]
Sorry, my bad. My Helm chart dependencies were not up-to-date. Once you do `helm dependency update` and do the `helm install` with the up-to-date dependency charts, you get a working system. Below is the image list.

```
      image: opea/chatqna:latest
      image: docker.io/opea/chatqna:latest
      image: opea/chatqna-conversation-ui:latest
      image: docker.io/opea/chatqna-conversation-ui:latest
      image: opea/dataprep-redis:latest
      image: docker.io/opea/dataprep-redis:latest
      image: nginx:1.27.1
      image: docker.io/library/nginx:1.27.1
      image: redis/redis-stack:7.2.0-v9
      image: docker.io/redis/redis-stack:7.2.0-v9
      image: opea/retriever-redis:latest
      image: docker.io/opea/retriever-redis:latest
      image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
      image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
      image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
      image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
      image: ghcr.io/huggingface/text-generation-inference:2.4.0-intel-cpu
      image: ghcr.io/huggingface/text-generation-inference:2.4.0-intel-cpu
```

In the UI there was no errors. I uploaded a `https://opea.dev/` content between first and second query, so the RAG works as well.

![Screenshot 2024-11-11 at 14 43 20](https://github.com/user-attachments/assets/e9c61361-2e00-4d8f-9a4e-5a77fbecd01a)
