### ISSUE TITLE
[ci-auto] GenAIExample ChatQnA,DocIndexRetriever,SearchQnA compose.yaml got changed.

### ISSUE THREAD

**Issue by daisy-ycguo** [opea-project/GenAIInfra#557]
## GenAIExample ChatQnA,DocIndexRetriever,SearchQnA compose.yaml got changed

Below files are changed in [this commit](https://github.com/opea-project/GenAIExamples/commit/9ff7df92029f17e7324edd1317c3508fb0d6480c)

- ChatQnA/docker_compose/intel/hpu/gaudi/compose.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_guardrails.yaml
- ChatQnA/docker_compose/intel/hpu/gaudi/compose_vllm.yaml
- DocIndexRetriever/docker_compose/intel/hpu/gaudi/compose.yaml
- SearchQnA/docker_compose/intel/hpu/gaudi/compose.yaml

Please verify if the helm charts and manifests need to be changed accordingly.

> This issue was created automatically by CI.

**Comment by lianhao** [comment]
already supported this
