### ISSUE TITLE
[ci-auto] adapt the docsum helmchart for new pipeline component

### ISSUE THREAD

**Issue by daisy-ycguo** [opea-project/GenAIInfra#579]
## GenAIExample DocSum compose.yaml got changed

Below files are changed in [this commit](https://github.com/opea-project/GenAIExamples/commit/eb91d1f054a8d8b65ac6fda0e039522bd877f7ac)

- DocSum/docker_compose/intel/cpu/xeon/compose.yaml
- DocSum/docker_compose/intel/hpu/gaudi/compose.yaml

Please verify if the helm charts and manifests need to be changed accordingly.

> This issue was created automatically by CI.

**Comment by yongfengdu** [comment]
Can't make helm chart support for 1.1 release since it's close to release date.
Will add support for 1.2 release.
