### ISSUE TITLE
[Feature] Apache APISIX support

### ISSUE THREAD

**Issue by joshuayao** [opea-project/GenAIInfra#595]
Authentication and Authorization with APISIX and OIDC based Identity provider (Keycloak)

#312

**Comment by lianhao** [comment]
What‘s this really about? I think @ckhened have already provided similar APISIX support at https://github.com/opea-project/GenAIInfra/tree/main/authN-authZ/auth-apisix

**Comment by joshuayao** [comment]
> What‘s this really about? I think [@ckhened](https://github.com/ckhened) have already provided similar APISIX support at https://github.com/opea-project/GenAIInfra/tree/main/authN-authZ/auth-apisix

This is a feature tracker of OPEA v1.2 roadmap on APISIX based AuthZ and AuthN. You could link the related PRs to this ticket.
