### ISSUE TITLE
[ChatQnA integration between GMC and OneClick]  Suggest new ServiceAccount and RBAC for all ChatQnA microservices

### ISSUE THREAD

**Issue by zhlsunshine** [opea-project/GenAIInfra#63]
Hi Team,

There should be the ServiceAccount RBAC setting for all ChatQnA microservices under a namespace, eg [gmc rbac](https://github.com/opea-project/GenAIInfra/blob/main/microservices-connector/templates/MicroChatQnA/gmc-rbac.yaml). However, I can not find such setting configurations in [ChatQnA](https://github.com/opea-project/GenAIInfra/tree/main/manifests/ChatQnA).  There are 2 suggestions for this:
1. New ServiceAccount yaml for all ChatQnA microservices in the same namespace instead using default.
2. New RBAC yaml for above new service ServiceAccount.
Please correct me if I'm incorrect.

**Comment by yongfengdu** [comment]
I'm not expert on security, so I think the best way is to leave the decision to k8s cluster admin(To modify default policy or create new one) or workload deployer.
To implement a RBAC for ChatQnA might improve the security a little by default, but without a thorough security review, it's hard to say how "Secure" our deployment is, and it should not be trusted by the deployer.
To summarize, I think implement the RBAC in current phase would introduce additional complexity and maintenance effort with little benefits.

**Comment by lianhao** [comment]
What's the rbac is used for here? If the rbac is used for GMC service to talk to k8s API server, I think this should be in the scope of GMC installation itself, not in any of the workload's scope.
