### ISSUE TITLE
GMC: Leverage OneClick yamls for the microservices

### ISSUE THREAD

**Issue by mkbhanda** [opea-project/GenAIInfra#64]
In the early days of the project with code, directories etc in flux, GMC developed its own microservice yamls. Now that things have stabilized and everything is part of the repo, time to move to the official oneClick yamls for the microservices.

**Comment by mkbhanda** [comment]
@zhlsunshine would appreciate your addressing this next week.

**Comment by zhlsunshine** [comment]
@mkbhanda okay, Malini, I'm focusing on it.

**Comment by chensuyue** [comment]
Can we close this issue?

**Comment by mkbhanda** [comment]
We have indeed been leveraging OneClick yamls in GMC and currently working on integrating the newly refactored versions.

**Comment by mkbhanda** [comment]
Done
