### ISSUE TITLE
[ChatQnA integration between GMC and OneClick] Need to remove the namespace for microservice endpoints.

### ISSUE THREAD

**Issue by zhlsunshine** [opea-project/GenAIInfra#77]
I notice that all microservice endpoints in [qna_configmap_xeon.yaml](https://github.com/opea-project/GenAIInfra/blob/main/manifests/ChatQnA/qna_configmap_xeon.yaml) and [qna_configmap_gaudi.yaml](https://github.com/opea-project/GenAIInfra/blob/main/manifests/ChatQnA/qna_configmap_gaudi.yaml) contains the service's namespace `default`,  it means that we only can deploy these microservices in `default` namespace. 
We should make user can deploy the ChatQnA demo in any namespace they like, so need to remove the namespace for microservice endpoints.
Thanks!

**Comment by leslieluyu** [comment]
Thanks for the message! We already noticed that, need to test and confirm after remove the "default".

**Comment by zhlsunshine** [comment]
Hi @leslieluyu,  just directly remove `default` may not be proper because it would lead to errors for services availability. Basically, it should be dynamical based on the deployment of microservices.  
According to above description, I think it should be hard for you to aware of the microservices deployment info. We can fetch these endpoints from GMC manager, and @KfreeZ can work on this. Moreover, you can remove these endpoints exposed in Configmap, does it make sense?

**Comment by KfreeZ** [comment]
> Hi @leslieluyu, just directly remove `default` may not be proper because it would lead to errors for services availability. Basically, it should be dynamical based on the deployment of microservices. According to above description, I think it should be hard for you to aware of the microservices deployment info. We may need to discuss it, does it make sense? @KfreeZ who can co-work on this.

yes, if there's a wildcard symbol to represent the changing factors would be better.
